name: Deploy Formula Page

# Manual trigger only - run this whenever you want to update the formula page
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for regenerating the page (optional)'
        required: false
        default: 'Manual update'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        run: |
          cd docs
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy formula page: ${{ github.event.inputs.reason }}"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
