name: Deploy Formula Page

# Manual trigger only - run this whenever you want to update the formula page
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for regenerating the page (optional)'
        required: false
        default: 'Manual update'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup directories
        run: |
          mkdir -p docs-build/api docs-build/formula

      - name: Tap and generate JSON
        run: |
          brew update
          brew tap alexandrelam/openscribe https://github.com/alexandrelam/homebrew-openscribe
          brew info --json=v2 alexandrelam/openscribe/openscribe > docs-build/api/openscribe.json

      - name: Generate HTML pages
        run: |
          # Install Node.js dependencies
          npm init -y >/dev/null 2>&1 || true
          npm install -s mustache >/dev/null 2>&1

          # Copy the template
          cp .github/formula-page-template.mustache docs-build/template.mustache

          # Generate the formula page
          node - <<'NODE'
          const fs = require('fs');
          const Mustache = require('mustache');

          // Read template and JSON
          const tpl = fs.readFileSync('docs-build/template.mustache', 'utf8');
          const data = JSON.parse(fs.readFileSync('docs-build/api/openscribe.json', 'utf8'));
          const formula = data.formulae[0];

          // Prepare context for template
          const ctx = {
            name: formula.name,
            desc: formula.desc || '',
            homepage: formula.homepage || '',
            version: formula.versions?.stable || '',
            license: formula.license || '',
            dependencies: formula.dependencies || [],
            build_dependencies: formula.build_dependencies || [],
            hasDeps: (formula.dependencies?.length > 0) || (formula.build_dependencies?.length > 0),
            bottles: Object.keys(formula.bottle?.stable?.files || {}),
            hasBottles: Object.keys(formula.bottle?.stable?.files || {}).length > 0,
            installCommand: 'brew tap alexandrelam/openscribe\nbrew install openscribe',
            githubUrl: formula.homepage,
            year: new Date().getFullYear()
          };

          // Render HTML
          const html = Mustache.render(tpl, ctx);

          // Write formula page
          fs.mkdirSync('docs-build/formula', { recursive: true });
          fs.writeFileSync('docs-build/formula/index.html', html);

          // Create index redirect
          const indexHtml = '<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="utf-8">\n  <meta http-equiv="refresh" content="0; url=./formula/">\n  <link rel="canonical" href="./formula/" />\n</head>\n<body>\n  <p>Redirecting to <a href="./formula/">OpenScribe formula page</a>...</p>\n</body>\n</html>';

          fs.writeFileSync('docs-build/index.html', indexHtml);
          NODE

      - name: Commit and push to gh-pages
        run: |
          cd docs-build
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy formula page: ${{ github.event.inputs.reason }}"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
