name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build for macOS ARM64 (Apple Silicon)
        run: |
          GOOS=darwin GOARCH=arm64 make build
          mv bin/openscribe bin/openscribe-darwin-arm64
        env:
          VERSION: v${{ steps.version.outputs.VERSION }}

      - name: Create archives
        run: |
          cd bin
          tar -czf openscribe-darwin-arm64.tar.gz openscribe-darwin-arm64
          shasum -a 256 openscribe-darwin-arm64.tar.gz > openscribe-darwin-arm64.tar.gz.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/openscribe-darwin-arm64.tar.gz
            bin/openscribe-darwin-arm64.tar.gz.sha256
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
